theme: jekyll-theme-hyde

---
layout: page
title: About
---

<!-- Default sidebar -->
<div class="sidebar">
  <div class="container sidebar-sticky">
    ...
  </div>
</div>

<!-- Modified sidebar -->
<div class="sidebar">
  <div class="container">
    ...
  </div>
</div>

<body class="theme-base-0b">
  ...
</body>
